# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYZC-Xxp-bvQg5ic37YYomwHIc9DuFNH
"""

import nltk
import pandas as pd
from nltk.chat.util import Chat, reflections

# Sample dataset
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 30, 22],
    'City': ['New York', 'Los Angeles', 'Chicago']
}

# Convert the dictionary into a DataFrame
df = pd.DataFrame(data)

# Define the pairs for the chatbot
pairs = [
    (r'hi|hello', ['Hello! How can I assist you today?']),
    (r'what is your name?', ['I am a chatbot created to assist you with basic questions.']),
    (r'how are you?', ['I am just a bot, but I am here to help you!']),
    (r'what can you do?', ['I can answer basic questions and display data from a provided dataset.']),
    (r'show data', ['Here is the data:\n%s' % df.to_string()]),
    (r'bye', ['Goodbye! Have a great day!'])
]

# Define a function for the chatbot response
def chatbot_response(user_input):
    chat = Chat(pairs, reflections)
    return chat.respond(user_input)

# Example usage
if __name__ == "__main__":
    nltk.download('punkt')
    while True:
        user_input = input("You: ")
        if user_input.lower() in ['bye', 'exit', 'quit']:
            print("Chatbot: Goodbye! Have a great day!")
            break
        response = chatbot_response(user_input)
        print(f"Chatbot: {response}")