# -*- coding: utf-8 -*-
"""TextConvert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laB4Yqv2aai8SHcEna1DqYvBg6J1wXgW
"""

#pip install deep-translator

from deep_translator import GoogleTranslator

file_path = '/content/text(1).txt'

with open(file_path, 'r') as file:
    text = file.read()

text

lang=input("Enter the language you want your text in")
translated = GoogleTranslator(source='auto', target='hi').translate(text)
translated